spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:\Users\Bartekk\Desktop\springApp\ciekawostki-db'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #  flyway:
#    enabled: false
  my.prop : 'test'
discovery:
  allow-multiple-discoveries-from-template: false
#szablon do tworzenia wiekszej liczy discovery na raz póki co na false(jest to nasze property)





